projectname    GumOpenGL

srcdir         src
exampledir     examples

findlibraries  OpenGL SELF GumGraphics GumCodecs GumPrimitives GumEssentials GumDesktop GumSystem GumMaths
headerfiles    
examples       

extralibraries_begin
minizip
extralibraries_end
