projectname    GumOpenGL

srcdir         src
exampledir     examples

findlibraries  SELF OpenGL GLEW GumSystem GumMaths GumEssentials
headerfiles    gum-opengl OpenGL/
examples       ObjectConversion

