projectname    GumOpenGL

srcdir         src
exampledir     examples

findlibraries  OpenGL SELF GumGraphics GumCodecs GumPrimitives GumEssentials GumDesktop GumSystem GumMaths
headerfiles    gum-opengl OpenGL/
examples       ObjectInfoWriter

extralibraries_begin
minizip
extralibraries_end
